In [1]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import timm

In [7]:
timm.list_models("vit*", pretrained=True)

['vit_base_patch8_224.augreg2_in21k_ft_in1k',
 'vit_base_patch8_224.augreg_in21k',
 'vit_base_patch8_224.augreg_in21k_ft_in1k',
 'vit_base_patch8_224.dino',
 'vit_base_patch14_dinov2.lvd142m',
 'vit_base_patch16_224.augreg2_in21k_ft_in1k',
 'vit_base_patch16_224.augreg_in1k',
 'vit_base_patch16_224.augreg_in21k',
 'vit_base_patch16_224.augreg_in21k_ft_in1k',
 'vit_base_patch16_224.dino',
 'vit_base_patch16_224.mae',
 'vit_base_patch16_224.orig_in21k_ft_in1k',
 'vit_base_patch16_224.sam_in1k',
 'vit_base_patch16_224_miil.in21k',
 'vit_base_patch16_224_miil.in21k_ft_in1k',
 'vit_base_patch16_384.augreg_in1k',
 'vit_base_patch16_384.augreg_in21k_ft_in1k',
 'vit_base_patch16_384.orig_in21k_ft_in1k',
 'vit_base_patch16_clip_224.laion2b',
 'vit_base_patch16_clip_224.laion2b_ft_in1k',
 'vit_base_patch16_clip_224.laion2b_ft_in12k',
 'vit_base_patch16_clip_224.laion2b_ft_in12k_in1k',
 'vit_base_patch16_clip_224.openai',
 'vit_base_patch16_clip_224.openai_ft_in1k',
 'vit_base_patch16_clip_224.op

In [6]:
model = timm.create_model("eva02_base_patch14_224.mim_in22k", pretrained=True)
print(model.default_cfg)
print(model.get_classifier())
print(model)

{'url': '', 'hf_hub_id': 'timm/eva02_base_patch14_224.mim_in22k', 'architecture': 'eva02_base_patch14_224', 'tag': 'mim_in22k', 'custom_load': False, 'input_size': (3, 224, 224), 'fixed_input_size': True, 'interpolation': 'bicubic', 'crop_pct': 0.9, 'crop_mode': 'center', 'mean': (0.48145466, 0.4578275, 0.40821073), 'std': (0.26862954, 0.26130258, 0.27577711), 'num_classes': 0, 'pool_size': None, 'first_conv': 'patch_embed.proj', 'classifier': 'head', 'license': 'mit'}
Identity()
Eva(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(14, 14), stride=(14, 14))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (rope): RotaryEmbeddingCat()
  (blocks): ModuleList(
    (0-11): 12 x EvaBlock(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): EvaAttention(
        (q_proj): Linear(in_features=768, out_features=768, bias=True)
        (k_proj): Linear(in_features=768, out_features=768, bias=False)
        (v_proj): Line

In [8]:
model = timm.create_model("vit_base_patch16_clip_224.laion2b_ft_in12k_in1k", pretrained=True)
print(model.default_cfg)
print(model.get_classifier())
print(model)

{'url': '', 'hf_hub_id': 'timm/vit_base_patch16_clip_224.laion2b_ft_in12k_in1k', 'architecture': 'vit_base_patch16_clip_224', 'tag': 'laion2b_ft_in12k_in1k', 'custom_load': False, 'input_size': (3, 224, 224), 'fixed_input_size': True, 'interpolation': 'bicubic', 'crop_pct': 0.95, 'crop_mode': 'center', 'mean': (0.48145466, 0.4578275, 0.40821073), 'std': (0.26862954, 0.26130258, 0.27577711), 'num_classes': 1000, 'pool_size': None, 'first_conv': 'patch_embed.proj', 'classifier': 'head'}
Linear(in_features=768, out_features=1000, bias=True)
VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16), bias=False)
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (patch_drop): Identity()
  (norm_pre): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_featu

In [12]:
model = timm.create_model("vit_base_patch16_clip_224.laion2b_ft_in12k_in1k", pretrained=False) 
model.head = nn.Sequential(# nn.BatchNorm1d(2048),
                        nn.Linear(in_features=768, out_features=256, bias=False),
                        nn.ReLU(inplace=True),
                        # nn.BatchNorm1d(256),
                        nn.Dropout(0.4),
                        nn.Linear(in_features=256, out_features=3, bias=False),
                        nn.LogSoftmax(dim=1))
print(model.default_cfg)    
print(model)   
print(model.get_classifier())

{'url': '', 'hf_hub_id': 'timm/vit_base_patch16_clip_224.laion2b_ft_in12k_in1k', 'architecture': 'vit_base_patch16_clip_224', 'tag': 'laion2b_ft_in12k_in1k', 'custom_load': False, 'input_size': (3, 224, 224), 'fixed_input_size': True, 'interpolation': 'bicubic', 'crop_pct': 0.95, 'crop_mode': 'center', 'mean': (0.48145466, 0.4578275, 0.40821073), 'std': (0.26862954, 0.26130258, 0.27577711), 'num_classes': 1000, 'pool_size': None, 'first_conv': 'patch_embed.proj', 'classifier': 'head'}
VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16), bias=False)
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (patch_drop): Identity()
  (norm_pre): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm

In [3]:
model = timm.create_model("resnet50.fb_ssl_yfcc100m_ft_in1k", pretrained=True)
print(model.default_cfg)
print(model.get_classifier())
print(model)

{'url': 'https://dl.fbaipublicfiles.com/semiweaksupervision/model_files/semi_supervised_resnet50-08389792.pth', 'hf_hub_id': 'timm/resnet50.fb_ssl_yfcc100m_ft_in1k', 'architecture': 'resnet50', 'tag': 'fb_ssl_yfcc100m_ft_in1k', 'custom_load': False, 'input_size': (3, 224, 224), 'fixed_input_size': False, 'interpolation': 'bilinear', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 1000, 'pool_size': (7, 7), 'first_conv': 'conv1', 'classifier': 'fc', 'license': 'cc-by-nc-4.0', 'origin_url': 'https://github.com/facebookresearch/semi-supervised-ImageNet1K-models'}
Linear(in_features=2048, out_features=1000, bias=True)
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (lay

In [9]:
model = timm.create_model("resnet50.fb_ssl_yfcc100m_ft_in1k", pretrained=False, num_classes=3)
model.fc = nn.Sequential(
    nn.Linear(in_features=2048, out_features=256, bias=False),
    nn.ReLU(inplace=True),
    nn.Dropout(0.4),
    nn.Linear(in_features=256, out_features=3, bias=False),
    nn.LogSoftmax(dim=1)
)
print(model.default_cfg)
print(model)
print(model.get_classifier())

{'url': 'https://dl.fbaipublicfiles.com/semiweaksupervision/model_files/semi_supervised_resnet50-08389792.pth', 'hf_hub_id': 'timm/resnet50.fb_ssl_yfcc100m_ft_in1k', 'architecture': 'resnet50', 'tag': 'fb_ssl_yfcc100m_ft_in1k', 'custom_load': False, 'input_size': (3, 224, 224), 'fixed_input_size': False, 'interpolation': 'bilinear', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 1000, 'pool_size': (7, 7), 'first_conv': 'conv1', 'classifier': 'fc', 'license': 'cc-by-nc-4.0', 'origin_url': 'https://github.com/facebookresearch/semi-supervised-ImageNet1K-models'}
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): C

In [27]:
l1 = nn.Linear(2, 3, bias=False)
l1.weight.data = 2 * torch.ones((3, 2))
print(l1.weight.data, l1.bias)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) None


In [28]:
d1 = torch.randn((2, 2, 2, 2, 2))
print(d1)

tensor([[[[[ 0.6686,  1.7234],
           [ 1.0820, -0.7666]],

          [[-0.6063, -0.6130],
           [ 0.7127, -0.8715]]],


         [[[-0.2614,  1.1844],
           [-0.4491, -0.0843]],

          [[-0.5783,  0.2204],
           [ 0.0388, -0.1187]]]],



        [[[[-0.3207,  1.4489],
           [ 1.9010, -0.4401]],

          [[ 0.3106, -0.3101],
           [-1.2597, -0.2923]]],


         [[[-1.2101, -1.4021],
           [ 0.2772,  0.3286]],

          [[ 0.3671,  0.9998],
           [-0.9491, -1.3918]]]]])


In [29]:
d2 = l1(d1)
print(d2)

tensor([[[[[ 4.7840e+00,  4.7840e+00,  4.7840e+00],
           [ 6.3068e-01,  6.3068e-01,  6.3068e-01]],

          [[-2.4386e+00, -2.4386e+00, -2.4386e+00],
           [-3.1757e-01, -3.1757e-01, -3.1757e-01]]],


         [[[ 1.8461e+00,  1.8461e+00,  1.8461e+00],
           [-1.0668e+00, -1.0668e+00, -1.0668e+00]],

          [[-7.1580e-01, -7.1580e-01, -7.1580e-01],
           [-1.5983e-01, -1.5983e-01, -1.5983e-01]]]],



        [[[[ 2.2564e+00,  2.2564e+00,  2.2564e+00],
           [ 2.9217e+00,  2.9217e+00,  2.9217e+00]],

          [[ 9.9802e-04,  9.9802e-04,  9.9802e-04],
           [-3.1040e+00, -3.1040e+00, -3.1040e+00]]],


         [[[-5.2244e+00, -5.2244e+00, -5.2244e+00],
           [ 1.2115e+00,  1.2115e+00,  1.2115e+00]],

          [[ 2.7337e+00,  2.7337e+00,  2.7337e+00],
           [-4.6819e+00, -4.6819e+00, -4.6819e+00]]]]],
       grad_fn=<UnsafeViewBackward0>)


In [96]:
a = torch.nn.Parameter(torch.tensor(2.))
b = torch.tensor(3.)
c = a * b
d = torch.nn.Parameter(torch.tensor(4.))
e = c * d
# e.detach_()
f = c * d
g = torch.nn.Parameter(torch.tensor(5.))
g.detach_()
h = f * g
i = e + h
print(f"a data = {a.data,a.requires_grad}, grad = {a.grad}")
print(f"b data = {b.data,b.requires_grad}, grad = {b.grad}")
print(f"c data = {c.data,c.requires_grad}, grad = {c.grad}")
print(f"d data = {d.data,d.requires_grad}, grad = {d.grad}")
print(f"e data = {e.data,e.requires_grad}, grad = {e.grad}")
print(f"f data = {f.data,f.requires_grad}, grad = {f.grad}")
print(f"g data = {g.data,g.requires_grad}, grad = {g.grad}")
print(f"h data = {h.data,h.requires_grad}, grad = {h.grad}")
print(f"i data = {i.data,i.requires_grad}, grad = {i.grad}")

# h.requires_grad_(False)
# h.detach_()
g.detach_()
f.retain_grad()
e.retain_grad()
i.backward()

print(f"a data = {a.data,a.requires_grad}, grad = {a.grad}")
print(f"b data = {b.data,b.requires_grad}, grad = {b.grad}")
print(f"c data = {c.data,c.requires_grad}, grad = {c.grad}")
print(f"d data = {d.data,d.requires_grad}, grad = {d.grad}")
print(f"e data = {e.data,e.requires_grad}, grad = {e.grad}")
print(f"f data = {f.data,f.requires_grad}, grad = {f.grad}")
print(f"g data = {g.data,g.requires_grad}, grad = {g.grad}")
print(f"h data = {h.data,h.requires_grad}, grad = {h.grad}")
print(f"i data = {i.data,i.requires_grad}, grad = {i.grad}")

a data = (tensor(2.), True), grad = None
b data = (tensor(3.), False), grad = None
c data = (tensor(6.), True), grad = None
d data = (tensor(4.), True), grad = None
e data = (tensor(24.), True), grad = None
f data = (tensor(24.), True), grad = None
g data = (tensor(5.), False), grad = None
h data = (tensor(120.), True), grad = None
i data = (tensor(144.), True), grad = None
a data = (tensor(2.), True), grad = 72.0
b data = (tensor(3.), False), grad = None
c data = (tensor(6.), True), grad = None
d data = (tensor(4.), True), grad = 36.0
e data = (tensor(24.), True), grad = 1.0
f data = (tensor(24.), True), grad = 5.0
g data = (tensor(5.), False), grad = None
h data = (tensor(120.), True), grad = None
i data = (tensor(144.), True), grad = None


In [7]:
x = torch.ones(1, requires_grad=True)
for i in range(5):
    print(x, x.data)  # 存储x的数据
    y = 2 * x
    print(y)
    reg = x.data * 100
    x.data = reg  # 只改变数据，不会改变计算图，但是自动微分机制被破坏了，将无法正确优化
    y.backward()
    print(x, x.grad)
    print(y)

tensor([1.], requires_grad=True) tensor([1.])
tensor([2.], grad_fn=<MulBackward0>)
tensor([100.], requires_grad=True) tensor([2.])
tensor([2.], grad_fn=<MulBackward0>)
tensor([100.], requires_grad=True) tensor([100.])
tensor([200.], grad_fn=<MulBackward0>)
tensor([10000.], requires_grad=True) tensor([4.])
tensor([200.], grad_fn=<MulBackward0>)
tensor([10000.], requires_grad=True) tensor([10000.])
tensor([20000.], grad_fn=<MulBackward0>)
tensor([1000000.], requires_grad=True) tensor([6.])
tensor([20000.], grad_fn=<MulBackward0>)
tensor([1000000.], requires_grad=True) tensor([1000000.])
tensor([2000000.], grad_fn=<MulBackward0>)
tensor([100000000.], requires_grad=True) tensor([8.])
tensor([2000000.], grad_fn=<MulBackward0>)
tensor([100000000.], requires_grad=True) tensor([100000000.])
tensor([2.0000e+08], grad_fn=<MulBackward0>)
tensor([1.0000e+10], requires_grad=True) tensor([10.])
tensor([2.0000e+08], grad_fn=<MulBackward0>)


In [67]:
a = torch.nn.Parameter(torch.tensor([1., 2.]))
b=2*a
b.detach_()
d = 3*a
c =torch.mean(d+b)
print("c data:",c)
c.backward()
print("a grad:", a.grad, a.requires_grad)
print("b grad:", b.grad, b.requires_grad)

c data: tensor(7.5000, grad_fn=<MeanBackward0>)
a grad: tensor([1., 1.]) True
b grad: None True


/opt/homebrew/Caskroom/miniconda/base/envs/tensor/lib/python3.9/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1656352453927/work/build/aten/src/ATen/core/TensorBody.h:482.)
  return self._grad


In [7]:
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = torch.Tensor([1.0])  # 初始权值
w.requires_grad = True  # 设置为需要计算梯度


def forward(x):
    y_pred = x * w
    return y_pred


def loss(y_pred, y):
    l = (y_pred - y) ** 2
    return l


def optim(w):
    w.data = w.data - 0.01 * w.grad.data


print('Predict (befortraining)', 4, forward(4).item())

for epoch in range(100):
    print('Epoch:', epoch)
    for x, y in zip(x_data, y_data):
        if w.grad is not None:
            w.grad.data.zero_()  # 等价于 optimizer.zero_grad()
        y_pred = forward(x)
        l = loss(y_pred, y)
        l.backward()
        print(f'x is {x}, y is {y}，l is {l.item()}')
        print(f'w is {w.item()}, w grad is {w.grad.item()}')
        optim(w)  # 等价于 optimizer.step() 的作用

print('Predict(after training)', 4, forward(4).item())

Predict (befortraining) 4 4.0
Epoch: 0
x is 1.0, y is 2.0，l is 1.0
w is 1.0, w grad is -2.0
x is 2.0, y is 4.0，l is 3.841600179672241
w is 1.0199999809265137, w grad is -7.840000152587891
x is 3.0, y is 6.0，l is 7.315943717956543
w is 1.0983999967575073, w grad is -16.228801727294922
Epoch: 1
x is 1.0, y is 2.0，l is 0.5465821623802185
w is 1.260688066482544, w grad is -1.478623867034912
x is 2.0, y is 4.0，l is 2.099749803543091
w is 1.2754743099212646, w grad is -5.796205520629883
x is 3.0, y is 6.0，l is 3.9987640380859375
w is 1.333436369895935, w grad is -11.998146057128906
Epoch: 2
x is 1.0, y is 2.0，l is 0.2987521290779114
w is 1.4534177780151367, w grad is -1.0931644439697266
x is 2.0, y is 4.0，l is 1.1476863622665405
w is 1.464349389076233, w grad is -4.285204887390137
x is 3.0, y is 6.0，l is 2.1856532096862793
w is 1.5072014331817627, w grad is -8.870372772216797
Epoch: 3
x is 1.0, y is 2.0，l is 0.16329261660575867
w is 1.5959051847457886, w grad is -0.8081896305084229
x is 2.0,

In [2]:
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.layers = nn.Sequential(nn.Linear(100, 300),
                  nn.GELU(),
                  nn.Linear(300, 100),
                  nn.Dropout(0.25)
                  )

    def forward(self, inputs, target=None):
        x = inputs
        outputs = self.layers(x)
        
        return outputs
    

test_net = TestNet